from . import ks_shopify_price_list
from . import ks_shopify_connector_instance
from . import ks_shopify_auto_sale_workflow_configuration
from . import ks_api_handler
from . import ks_shopify_logs
from . import ks_queue_jobs
from . import ks_res_partners
from . import ks_shopify_res_partner
from . import ks_ir_cron
from . import ks_shopify_collections
from . import ks_shopify_product_template
from . import ks_shopify_product_images
from . import ks_shopify_product_variants
from . import ks_shopify_attribute
from . import ks_shopify_attribute_values
from . import ks_shopify_price_rule_discounts
from . import dashboard
from . import ks_email_report
from . import ks_webhook_configuration
from . import ks_shopify_payment_gateway
from . import ks_shopify_sale_order
from . import ks_account_move
from . import ks_shopify_sale_order_reporting
from . import ks_global_record_mapping
from . import ks_res_config
from . import ks_shopify_locations
